version: '3.8'
services:
  db:
    build:
      context: ./backend
      dockerfile: Dockerfile.db
    container_name: innovatesphere-db
    restart: always
    environment:
      POSTGRES_USER: innovate_admin
      POSTGRES_PASSWORD: innovate_pass_2025
      POSTGRES_DB: innovatesphere_dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: